version: "3"
name: "6_pay_my_buddy"

services:
  postgres:
    image: "docker.io/postgres:latest"
    restart: "unless-stopped"
    environment:
      - "POSTGRES_DB=${DATABASE_DB}"
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "PGPORT=${DATABASE_PORT}"
    ports:
      - "5432:${DATABASE_PORT}"

  migration:
    depends_on:
      - "postgres"
    restart: "no"
    environment:
      - "DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOSTNAME}:${DATABASE_PORT}/${DATABASE_DB}"
    volumes:
      - "./migrations:/app/migrations"
    build:
      context: "."
      dockerfile: "./docker/Dockerfile.migration"

  backend:
    restart: "unless-stopped"
    env_file: ".env"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - "./src:/app/src"
    build:
      context: "."
      dockerfile: "./docker/Dockerfile.backend"

volumes:
  migrations:
  backend:
