ALTER TABLE public."transaction" DROP CONSTRAINT IF EXISTS FK_RECEIVER CASCADE;

ALTER TABLE public."transaction"
ADD CONSTRAINT FK_RECEIVER FOREIGN KEY (id_receiver) REFERENCES public."user" (id) MATCH FULL ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE public."transaction" DROP CONSTRAINT IF EXISTS FK_SENDER CASCADE;

ALTER TABLE public."transaction"
ADD CONSTRAINT FK_SENDER FOREIGN KEY (id_sender) REFERENCES public."user" (id) MATCH FULL ON DELETE CASCADE ON UPDATE CASCADE;
