ALTER TABLE public."bank_transaction" DROP CONSTRAINT IF EXISTS FK_USER CASCADE;

ALTER TABLE public."bank_transaction"
ADD CONSTRAINT FK_USER FOREIGN KEY (id_user) REFERENCES public."user" (id) MATCH FULL ON DELETE
SET NULL ON UPDATE CASCADE;
